""""""


DATASET_PATH = "./VMMRdb"
CHECKPOINT_PATH = "./models/checkpoints/checkpoint"
CSV_FILE_PATH = "./dataset.csv"
BATCH_SIZE = 16
VAL_SPLIT_SIZE = 0.2
RANDOM_SEED = 42
NUM_EPOCHS = 5
LEARNING_RATE = 0.001
MOMENTUM = 0.9
WEIGHT_DECAY = 0.2
